name: Client Cypress Tests

on:
  push:
    branches:
      - main

jobs:
  run-cypress-tests:
    runs-on: cs5500-self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies for Client
        working-directory: client
        run: npm install

      - name: Install Dependencies for Server
        working-directory: server
        run: npm install

      - name: Remove Old Database
        working-directory: server
        run: npm run remove_db

      - name: Populate Database
        working-directory: server
        run: npm run populate_db

      - name: Start Server
        working-directory: server
        run: |
          nohup npm start & sleep 10 # wait for the server to start

      - name: Start Client
        working-directory: client
        run: |
          nohup npm start & sleep 10 # wait for the client to start

      - name: Run Cypress Tests
        working-directory: client
        run: npx cypress run --spec cypress/e2e/
