name: Client Cypress Tests

on:
  push:
    branches:
      - main

jobs:
    run-cypress-tests:
        runs-on: cs5500-self-hosted
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3
            
            - name: Remove old database
              working-directory: server
              run: npm run remove_db

            - name: Populate Database
              working-directory: server
              run: npm run populate_db
            
            - name: Install Dependencies for client
              working-directory: client
              run: npm install
            
            - name: Install Dependencies for server
              working-directory: server
              run: npm install

            - name: Start Client
              working-directory: server
              run: npm start

            - name: Start Server
              working-directory: server
              run: npm start

            - name: Run Cypress Tests
              working-directory: client
              run: npx cypress run --spec cypress/e2e/

            
            
            
            
