name: Fake Stack CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  "run-jest-tests":
    runs-on: cs5500-self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
       # Step 6: Install dependencies in the client folder
      - name: Install Client Dependencies
        working-directory: client
        run: npm force install

      # Step 7: Run Cypress tests
      - name: Run Cypress Tests
        working-directory: client
        run: npx cypress run --spec "cypress/e2e/**/*.cy.js"
      - name: Install Dependencies
        working-directory: server
        run: npm install
        
      - name: Delete old database
        working-directory: server
        run: npm run remove_db

      - name: Seed database
        working-directory: server
        run: npm run populate_db

      - name: Run Tests
        working-directory: server
        run: npm run test
